Only use results from GetWindowProperty if it returned success
Since Xlib prior to 1.6 didn't always clear values on failure, don't
assume they're safe to use unless we succeeded.

Reported by Oracle Parfait 1.5.1:
Error: Uninitialised memory (CWE 456)
   Possible access to uninitialised memory '&after'
        at line 328 of xsetroot.c in function 'FixupState'.
          &after allocated at line 317.
   Possible access to uninitialised memory '&data'
        at line 330 of xsetroot.c in function 'FixupState'.
          &data allocated at line 318.
   Possible access to uninitialised memory '&format'
        at line 328 of xsetroot.c in function 'FixupState'.
          &format allocated at line 316.
   Possible access to uninitialised memory '&length'
        at line 328 of xsetroot.c in function 'FixupState'.
          &length allocated at line 317.
   Possible access to uninitialised memory '&type'
        at line 328 of xsetroot.c in function 'FixupState'.
          &type allocated at line 315.
        at line 331 of xsetroot.c in function 'FixupState'.
          &type allocated at line 315.

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Reviewed-by: Hans de Goede <hdegoede@redhat.com>